CREATE TABLE IF NOT EXISTS diagnostic_logs (
	id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
	type TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	log JSONB NOT NULL,
	CONSTRAINT pk_diagnostic_logs PRIMARY KEY(id, type)
);
