CREATE TABLE IF NOT EXISTS deployment_logs (
	id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
	deployment_id BIGINT NOT NULL UNIQUE REFERENCES deployments(id) ON DELETE CASCADE,
	log TEXT,
	CONSTRAINT pk_deployment_logs PRIMARY KEY(id, deployment_id)
);
