CREATE TABLE IF NOT EXISTS projects (
	id BIGINT GENERATED ALWAYS AS IDENTITY,
	repository TEXT NOT NULL,
	requires_authn BOOLEAN NOT NULL DEFAULT FALSE,
	username TEXT,
	password TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT pk_projects PRIMARY KEY(id, repository)
);

CREATE OR REPLACE TRIGGER projects_moddatetime
	BEFORE UPDATE ON projects
	FOR EACH ROW
	EXECUTE PROCEDURE moddatetime(updated_at);
