CREATE TABLE IF NOT EXISTS webhooks (
	id BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
	type SMALLINT NOT NULL,
	deleted BOOLEAN NOT NULL DEFAULT FALSE,
	CONSTRAINT pk_webhooks PRIMARY KEY(id, type)
);