# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  start:
    desc: Run API
    cmds:
      - go run -tags assert .

  dev:
    desc: Run development API
    cmds:
      - gow run -tags assert .

  build:
    desc: Build API
    cmds:
      - go build .

  create-migration:
    desc: Create a new migration
    cmds:
      - migrate create -ext sql -dir db/pg/schema -seq {{.CLI_ARGS}}
      - migrate create -ext sql -dir db/sqlite/schema -seq {{.CLI_ARGS}}

  bundle-migrations:
    desc: Bundle migrations in executable
    cmds:
      - go get github.com/jteeuwen/go-bindata/...
      - go install github.com/jteeuwen/go-bindata/...
      - go mod tidy
      - cd db/pg/schema && go-bindata -pkg migrations .
      - cd db/sqlite/schema && go-bindata -pkg migrations .

  create-query:
    desc: Create a new query
    cmds:
      - touch db/pg/queries/{{.CLI_ARGS}}.sql
      - touch db/sqlite/queries/{{.CLI_ARGS}}.sql

  generate-models:
    desc: Generate DB models
    cmds:
      - sqlc generate

  generate-swagger:
    desc: Generate Swagger documentation
    cmds:
      - swag init -d ./,./handlers/projects
      - swag fmt

  generate-env-docs:
    desc: Generate docs for env configuration
    cmds:
      - FERRITE_MODE="usage/markdown" go run . > CONFIG.md

  generate-all:
    desc: Run all generators
    deps:
      - generate-models
      - generate-swagger
      - bundle-migrations
      - generate-env-docs

  run-temporal-dev:
    desc: Run Temporal dev server
    cmds:
      - docker run --rm -p 7233:7233 -p 8233:8233 temporalio/temporal server start-dev --ip 0.0.0.0

  run-pg:
    desc: Run Postgres for development
    cmds:
      - echo "Connection string = postgresql://postgres:mysecretpassword@localhost/buang?sslmode=disable"
      - echo "User = postgres"
      - echo "Password = mysecretpassword"
      - echo "Database = buang"
      - docker run --rm -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -e POSTGRES_DB=buang postgres

  deploy-prod:
    desc: Deploy compose service in production
    cmds:
      - mkdir -p /deployments
      - echo "Buang depends on Temporal, you can use Temporal Cloud or self host it by following the docs at https://docs.temporal.io/self-hosted-guide"
      - docker-compose -f docker-compose.prod.yml up

  # TODO: base64 encoded token so that we don't trip github secret scanning for now
  # TODO: from repo secrets
  test-int-ci:
    desc: Run tests
    cmds:
      - GO_ENV="test" BUANG_TRAEFIK_DYNAMIC_CONFIG_DIR="/tmp/buang_test" TESTCONTAINERS_REUSE_ENABLE=false BUANG_TEST_GITHUB_USER="nmathew98" BUANG_TEST_GITHUB_PAT="$(echo 'Z2l0aHViX3BhdF8xMUFORVFHSUEwRjNac0dMazZoNFpHX283YmR6TTdldUllbm5xWXdOWjlhcVJaaEN6YmdJa2JiUFlVc2pxR1FUTldVUkU1T1dJSmYyWmFYdWhLCg==' | base64 -d)" go test -count=1 {{.CLI_ARGS}} ./tests/integration_tests

  # TODO: base64 encoded token so that we don't trip github secret scanning for now
  # TODO: from repo secrets
  test-fitness-ci:
    desc: Run tests
    cmds:
      - GO_ENV="test" BUANG_TRAEFIK_DYNAMIC_CONFIG_DIR="/tmp/buang_test" TESTCONTAINERS_REUSE_ENABLE=false BUANG_TEST_GITHUB_USER="nmathew98" BUANG_TEST_GITHUB_PAT="$(echo 'Z2l0aHViX3BhdF8xMUFORVFHSUEwRjNac0dMazZoNFpHX283YmR6TTdldUllbm5xWXdOWjlhcVJaaEN6YmdJa2JiUFlVc2pxR1FUTldVUkU1T1dJSmYyWmFYdWhLCg==' | base64 -d)" go test -count=1 {{.CLI_ARGS}} ./tests/fitness_tests

  # TODO: base64 encoded token so that we don't trip github secret scanning for now
  # TODO: from repo secrets
  test-int:
    desc: Run tests
    cmds:
      - GO_ENV="test" TESTCONTAINERS_REUSE_ENABLE=false BUANG_TEST_GITHUB_USER="nmathew98" BUANG_TEST_GITHUB_PAT="$(echo 'Z2l0aHViX3BhdF8xMUFORVFHSUEwRjNac0dMazZoNFpHX283YmR6TTdldUllbm5xWXdOWjlhcVJaaEN6YmdJa2JiUFlVc2pxR1FUTldVUkU1T1dJSmYyWmFYdWhLCg==' | base64 -d)" go test -count=1 {{.CLI_ARGS}} ./tests/integration_tests

  # TODO: base64 encoded token so that we don't trip github secret scanning for now
  # TODO: from repo secrets
  test-int-watch:
    desc: Run tests in watch mode
    cmds:
      - GO_ENV="test" TESTCONTAINERS_REUSE_ENABLE=false BUANG_TEST_GITHUB_USER="nmathew98" BUANG_TEST_GITHUB_PAT="$(echo 'Z2l0aHViX3BhdF8xMUFORVFHSUEwRjNac0dMazZoNFpHX283YmR6TTdldUllbm5xWXdOWjlhcVJaaEN6YmdJa2JiUFlVc2pxR1FUTldVUkU1T1dJSmYyWmFYdWhLCg==' | base64 -d)" gow test -count=1 {{.CLI_ARGS}} ./tests/integration_tests

  # TODO: base64 encoded token so that we don't trip github secret scanning for now
  # TODO: from repo secrets
  test-fitness:
    desc: Run tests
    cmds:
      - GO_ENV="test" TESTCONTAINERS_REUSE_ENABLE=false BUANG_TEST_GITHUB_USER="nmathew98" BUANG_TEST_GITHUB_PAT="$(echo 'Z2l0aHViX3BhdF8xMUFORVFHSUEwRjNac0dMazZoNFpHX283YmR6TTdldUllbm5xWXdOWjlhcVJaaEN6YmdJa2JiUFlVc2pxR1FUTldVUkU1T1dJSmYyWmFYdWhLCg==' | base64 -d)" go test -count=1 {{.CLI_ARGS}} ./tests/fitness_tests

  # TODO: base64 encoded token so that we don't trip github secret scanning for now
  # TODO: from repo secrets
  test-fitness-watch:
    desc: Run fitness tests in watch mode
    cmds:
      - GO_ENV="test" TESTCONTAINERS_REUSE_ENABLE=false BUANG_TEST_GITHUB_USER="nmathew98" BUANG_TEST_GITHUB_PAT="$(echo 'Z2l0aHViX3BhdF8xMUFORVFHSUEwRjNac0dMazZoNFpHX283YmR6TTdldUllbm5xWXdOWjlhcVJaaEN6YmdJa2JiUFlVc2pxR1FUTldVUkU1T1dJSmYyWmFYdWhLCg==' | base64 -d)" gow test -count=1 {{.CLI_ARGS}} ./tests/fitness_tests
