name: Deploy services

on:
  push:
    tags:
      - 'v*'
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]

    if: ${{ always() }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Short sha'
        id: vars_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: skulpture/buang-api
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix= ${{ matrix.os == 'ubuntu-latest' && 'amd64' || 'arm64' }}
          sep-tags: ','
            
      - name: "Build Docker image: buang-api"
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:api"
          platforms: ${{ matrix.os == 'ubuntu-latest' && 'linux/amd64' || 'linux/arm64' }}
          push: true
          build-args: VERSION=${{ steps.vars_sha.outputs.short_sha }}
          tags: ${{ steps.meta.outputs.tags }}

  docker-push:
    needs: build

    strategy:
      matrix:
        image: [skulpture/buang-api]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta-amd64
        uses: docker/metadata-action@v5
        with:
          images: skulpture/buang-api
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=amd64
          sep-tags: ','

      - name: Docker meta
        id: meta-arm64
        uses: docker/metadata-action@v5
        with:
          images: skulpture/buang-api
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          flavor: |
            latest=auto
            prefix=
            suffix=arm64
          sep-tags: ','
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: skulpture/buang-api
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          sep-tags: ','

      - name: Push ${{ matrix.image }}
        uses: Noelware/docker-manifest-action@v1
        with:
          inputs: ${{ steps.meta-amd64.outputs.tags }},${{ steps.meta-arm64.outputs.tags }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
