name: Release

on:
  pull_request:
    branches:
      - master
      - staging/*
      - canary/*
    types: [closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}
  cancel-in-progress: false

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true }}
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: zwaldowski/match-label-action@v6
        id: release-label
        with:
          allowed: release/major, release/minor, release/patch

      - uses: zwaldowski/semver-release-action@v6
        id: bump
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump: ${{ case(
            contains(github.base_ref, 'canary') && contains(steps.release-label.outputs.match, 'patch'), 'prepatch',
            contains(github.base_ref, 'canary') && contains(steps.release-label.outputs.match, 'minor'), 'preminor',
            contains(github.base_ref, 'canary') && contains(steps.release-label.outputs.match, 'major'), 'premajor',
            contains(github.base_ref, 'staging') && contains(steps.release-label.outputs.match, 'patch'), 'prepatch',
            contains(github.base_ref, 'staging') && contains(steps.release-label.outputs.match, 'minor'), 'preminor',
            contains(github.base_ref, 'staging') && contains(steps.release-label.outputs.match, 'major'), 'premajor',
            contains(github.base_ref, 'master') && contains(steps.release-label.outputs.match, 'patch'), 'patch',
            contains(github.base_ref, 'master') && contains(steps.release-label.outputs.match, 'minor'), 'minor',
            contains(github.base_ref, 'master') && contains(steps.release-label.outputs.match, 'major'), 'major',
            'prerelease') }}
          dry_run: true
          per_branch: true
          preid: ${{ case(
            contains(github.base_ref, 'canary'), 'canary',
            contains(github.base_ref, 'staging'), 'staging',
            '') }}

      - uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --verbose --tag ${{ steps.bump.outputs.version_tag }} --output CHANGELOG.md

      - uses: orhun/git-cliff-action@v4
        id: unreleased-changelog
        with:
          config: cliff.toml
          args: --verbose --unreleased --tag ${{ steps.bump.outputs.version_tag }}

      - uses: iarekylew00t/verified-bot-commit@v2
        id: commit-changelog
        with:
          message: "chore(${{ steps.bump.outputs.version_tag }}): update changelog"
          ref: ${{ github.base_ref }}
          files: |
            CHANGELOG.md

      - uses: zwaldowski/semver-release-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump: ${{ case(
            contains(github.base_ref, 'canary') && contains(steps.release-label.outputs.match, 'patch'), 'prepatch',
            contains(github.base_ref, 'canary') && contains(steps.release-label.outputs.match, 'minor'), 'preminor',
            contains(github.base_ref, 'canary') && contains(steps.release-label.outputs.match, 'major'), 'premajor',
            contains(github.base_ref, 'staging') && contains(steps.release-label.outputs.match, 'patch'), 'prepatch',
            contains(github.base_ref, 'staging') && contains(steps.release-label.outputs.match, 'minor'), 'preminor',
            contains(github.base_ref, 'staging') && contains(steps.release-label.outputs.match, 'major'), 'premajor',
            contains(github.base_ref, 'master') && contains(steps.release-label.outputs.match, 'patch'), 'patch',
            contains(github.base_ref, 'master') && contains(steps.release-label.outputs.match, 'minor'), 'minor',
            contains(github.base_ref, 'master') && contains(steps.release-label.outputs.match, 'major'), 'major',
            'prerelease') }}
          dry_run: false
          sha: ${{ steps.commit-changelog.outputs.commit }}
          per_branch: true
          preid: ${{ case(
            contains(github.base_ref, 'canary'), 'canary',
            contains(github.base_ref, 'staging'), 'staging',
            '') }}

      - uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ github.base_ref != 'master' }}
          name: ${{ steps.bump.outputs.version_tag }}
          tag_name: ${{ steps.bump.outputs.version_tag }}
          target_commitish: ${{ github.base_ref }}
          generate_release_notes: false
          body: ${{ steps.unreleased-changelog.outputs.content }}
