name: Test services

on:
  push:
    branches: [master, staging, dev]
  pull_request:
    branches: [master, staging, dev]
  workflow_dispatch:

jobs:
  test:
    environment: "test"

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'api/go.mod'

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Test API
        working-directory: api
        run: |
            task test-ci -- -v
